tenancy_ocid          = "ocid1.tenancy.oc1..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
user_ocid             = "ocid1.user.oc1..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
rsa_private_key_path  = "oracle-rsa.pem"
fingerprint           = "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"
region_identifier     = "eu-madrid-1"
ssh_public_key_path   = "foundry-ssh.pub"
alert_rule_recipients = "mail@mail.com"
